networks:
  public_gateway:
    external: true

services:
  api:
    container_name: api
    image: registry.nautilusinvesting.com/datalab-api:v13
    environment:
      - PORT=3001
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DATABASE_PATH=/app/data/nautilus.db
    volumes:
      - nautilus_db:/app/data
    restart: always
    networks:
      - public_gateway
  ui:
    container_name: data
    image: registry.nautilusinvesting.com/datalab-ui:v8
    depends_on:
      - api
    restart: always
    networks:
      - public_gateway
volumes:
  nautilus_db:
